spring.application.name=task-management-system
spring.profiles.active=local

azentrix.app.jwtExpirationMs=86400000
azentrix.app.jwtSecret=${JWT_SECRET}

# Mail Configuration
spring.mail.host=${SMTP_HOST:smtp.example.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:user}
spring.mail.password=${SMTP_PASSWORD:password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true